### ISSUE TITLE
"Stealth" Deletion method

### ISSUE THREAD

**Issue by maloryware** [Ramixin/Mixson#1]
Hi there! Amazing library, absolutely loved it. I've noticed there's no mention of DeletionEvents nor how they behave in the wiki, however?
Simply requesting the registerDeletionEvent method and the DeletionEvent Functional Interface's behaviors to be explained.

**Comment by Ramixin** [comment]
ah yes! I forgot to update the wiki... I've have it up within the hour (hopefully not in two)

**Comment by Ramixin** [comment]
I have updated the wiki to V:0.1.0. Feel free to reopen this issue if there are any other issues
